### ISSUE TITLE
OR condition

### ISSUE THREAD

**Issue by indapublic** [javer/JaverSphinxBundle#4]
Hey! Thanks for your awesome library.
Have a question.
Is it possible to do OR condition? I want to find all occurrences with "foo" and "bar" for example

```
->match(["title", "content", "tag"], "foo")
->match(["title", "content", "tag"], "bar")
```

Something like that, but it works like AND condition.

**Comment by indapublic** [comment]
Tried with `->match(["title", "content", "tag"], "foo | bar")` but not worked

**Comment by javer** [comment]
@indapublic If you want to use [Extended query syntax](http://sphinxsearch.com/docs/archives/2.2.10/extended-syntax.html) as the value for `match`, you should specify true as the third argument:
```php
->match(['title', 'content', 'tag'], 'foo | bar', true)
```
will be compiled to:
```sql
MATCH("@(title,content,tag) foo | bar")
```
Please note that you should sanitize user input to avoid injection, you can see in method `Query::quoteMatch()` all symbols which should be escaped. Passing true to the third argument of `Query::match()` disables automatic escaping.

**Comment by indapublic** [comment]
Oh, stupid me. Sorry. Found 'setQuery' but not third argument for 'match'. Thank you!
