### ISSUE TITLE
Symfony 5 support

### ISSUE THREAD

**Issue by JohanDevGit** [javer/JaverSphinxBundle#5]
Hello

i see the bundle is Symfony 5 compliant but i had a problem at installation

The parameter "javer_sphinx.config_path" has a dependency on a non-existent parameter "kernel.root_dir". Did you mean one of these: "kernel.project_dir", "kernel.cache_dir", "kernel.logs_dir"?

i modified vendor\javer\sphinx-bundle\DependencyInjection\Configuration.php

line 32 is 
`->scalarNode('config_path')->defaultValue($conf)->end()`

and insert  after line 27 

`        if (\Symfony\Component\HttpKernel\Kernel::MAJOR_VERSION >= 4) {
            $conf = '%kernel.root_dir%/config/sphinx.conf';
        }
`
`        if (\Symfony\Component\HttpKernel\Kernel::MAJOR_VERSION >= 5) {
            $conf = '%kernel.project_dir%/config/sphinx.conf';
        }`

and then `composer require javer/sphinx-bundle` again

and it worked
Kind regards

**Comment by iliyaisd** [comment]
I've got the same problem.

**Comment by javer** [comment]
Thank you for the report! Fixed in [v1.4.0](https://github.com/javer/JaverSphinxBundle/releases/tag/v1.4.0)
